### ISSUE TITLE
Create A Category

### ISSUE THREAD

**Issue by Snc1730** [NSS-Evening-E22/starlight-stalkers-rare#10]
Given a user is on the category list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the category should be added
And the category list should update

## DevNotes
|Action | Description |
|--------|-------------|
|`GIVEN`| The user is on the category list page, there should be a create form on the right side of the page |
|`WHEN`|  they fill out the form and submit |
|`THEN`| the category should be added |
|`AND`| the category list should update |

**Comment by rjm3q** [comment]
`app.MapPost("/Categories/{Id}", (Categories Category) =>
{
    Category.Id = Category.Max(cat => cat.Id) + 1;
    Category.Add(Category)
    return Results.Ok(Categories);
});`
