### ISSUE TITLE
View Post Details

### ISSUE THREAD

**Issue by Snc1730** [NSS-Evening-E22/starlight-stalkers-rare#13]
Given a user is looking at a list of posts
When they click on the post title
Then they should be directed to the post detail page
And the details should include:

 Title
 Author's name
 Category
 Publication date
 Content

**Comment by jjBaltz** [comment]
As a user I, I want to click on a singular post to see all of the details of it.

**Dev Notes**
- Server Side: Create an endpoint API call using `app.MapGet` to the endpoint `("/posts/{id}"` with the parameters of the id. 
- Return only the post whose id the user grabs and display it if it is a valid id, if not valid, return `Results.NotFound()`
- Details should include the `Title`, Author's Name of Post (grab the User's  `FirstName`  and  `LastName`  values), `Category` , `PublicationDate` , and `Content` .
