### ISSUE TITLE
View All Posts

### ISSUE THREAD

**Issue by Snc1730** [NSS-Evening-E22/starlight-stalkers-rare#14]
Given the user clicks on the "Posts" link in the navbar
When they are directed to the /posts page
Then they should see a list of all posts, with the post title, author name, and category
And the posts should be ordered by the date they were added, most recent first

**Comment by jjBaltz** [comment]
- As a user I should be able to view all Posts of the app regardless of tags or categories.

**Dev Notes**
- Server Side: In `program.cs` create an API call using `app.MapGet` for `("/posts")` and return the posts.
- Make sure the endpoint is up and running in Swagger or Postman.
